---
name: 'Googletest Action'
description: 'GitHub action to build and run Googletest cases'
author: 'Grahame White'
inputs:
  test-path:
    description: 'relative path to directory containing test code'
    required: true
    default: 'tests'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/grahame-student/gtest_action:v0.0.2'
  args:
    - ${{ inputs.test-path }}
branding:
  icon: 'code'
  colour: 'orange'
